### ISSUE TITLE
OpenBiodiv returns http code 401 (unauthorized) when requesting query results

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#122]
For some reason, OpenBiodiv SparQL endpoint no longer returns results. Instead an error code 401 (unauthorized) is returned.

some example errors include:

```
java.io.IOException: failed to execute query [PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX prism: <http://prismstandard.org/namespaces/basic/2.0/>
PREFIX doco: <http://purl.org/spar/doco/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
select ?name ?rank ?id ?kingdom ?phylum ?class ?order ?family ?genus ?specificEpithet where { {
    BIND(<http://openbiodiv.net/6A54156A-BE5C-44D7-A9E3-3902DA4CCFAC> AS ?id). 
     ?id <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/TaxonomicNameUsage>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/specificEpithet> ?specificEpithet.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/genus> ?genus.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/family> ?family.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/order> ?order. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/class> ?class. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/phylum> ?phylum.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/kingdom> ?kingdom.}
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?taxon.
      ?taxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/verbatimTaxonRank> ?rank.}
      ?taxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }    UNION
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?btaxon.
      ?btaxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      ?btaxon <http://openbiodiv.net/hasGbifTaxon> ?taxon.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/taxonRank> ?rank.}
      ?btaxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }  } }]

	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:27)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.doLookup(OpenBiodivUtil.java:58)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.retrieveTaxonHierarchyById(OpenBiodivUtil.java:21)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.retrieveTaxonSpecies(OpenBiodivUtilTest.java:40)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: failed to get [http://graph.openbiodiv.net/repositories/OpenBiodiv2020?query=PREFIX%20fabio:%20%3Chttp://purl.org/spar/fabio/%3E%0APREFIX%20prism:%20%3Chttp://prismstandard.org/namespaces/basic/2.0/%3E%0APREFIX%20doco:%20%3Chttp://purl.org/spar/doco/%3E%0APREFIX%20dc:%20%3Chttp://purl.org/dc/elements/1.1/%3E%0Aselect%20?name%20?rank%20?id%20?kingdom%20?phylum%20?class%20?order%20?family%20?genus%20?specificEpithet%20where%20%7B%20%7B%0A%20%20%20%20BIND(%3Chttp://openbiodiv.net/6A54156A-BE5C-44D7-A9E3-3902DA4CCFAC%3E%20AS%20?id).%20%0A%20%20%20%20%20?id%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/TaxonomicNameUsage%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/specificEpithet%3E%20?specificEpithet.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/genus%3E%20?genus.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/family%3E%20?family.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/order%3E%20?order.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/class%3E%20?class.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/phylum%3E%20?phylum.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/kingdom%3E%20?kingdom.%7D%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?taxon.%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/verbatimTaxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%20%20UNION%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?btaxon.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://openbiodiv.net/hasGbifTaxon%3E%20?taxon.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/taxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%7D%20%7D]
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:134)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:127)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.lambda$getResourceServiceTest$0(OpenBiodivUtilTest.java:70)
	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:25)
	... 28 more
Caused by: org.apache.http.client.HttpResponseException: status code: 401
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:66)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:52)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:132)
	... 31 more


java.io.IOException: failed to execute query [PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX prism: <http://prismstandard.org/namespaces/basic/2.0/>
PREFIX doco: <http://purl.org/spar/doco/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
select ?name ?rank ?id ?kingdom ?phylum ?class ?order ?family ?genus ?specificEpithet where { {
    BIND(<http://openbiodiv.net/4B689A17-2541-4F5F-A896-6F0C2EEA3FB4> AS ?id). 
     ?id <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/TaxonomicNameUsage>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/specificEpithet> ?specificEpithet.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/genus> ?genus.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/family> ?family.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/order> ?order. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/class> ?class. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/phylum> ?phylum.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/kingdom> ?kingdom.}
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?taxon.
      ?taxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/verbatimTaxonRank> ?rank.}
      ?taxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }    UNION
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?btaxon.
      ?btaxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      ?btaxon <http://openbiodiv.net/hasGbifTaxon> ?taxon.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/taxonRank> ?rank.}
      ?btaxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }  } }]

	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:27)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.doLookup(OpenBiodivUtil.java:58)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.retrieveTaxonHierarchyById(OpenBiodivUtil.java:21)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.retrieveTaxonFamily(OpenBiodivUtilTest.java:26)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: failed to get [http://graph.openbiodiv.net/repositories/OpenBiodiv2020?query=PREFIX%20fabio:%20%3Chttp://purl.org/spar/fabio/%3E%0APREFIX%20prism:%20%3Chttp://prismstandard.org/namespaces/basic/2.0/%3E%0APREFIX%20doco:%20%3Chttp://purl.org/spar/doco/%3E%0APREFIX%20dc:%20%3Chttp://purl.org/dc/elements/1.1/%3E%0Aselect%20?name%20?rank%20?id%20?kingdom%20?phylum%20?class%20?order%20?family%20?genus%20?specificEpithet%20where%20%7B%20%7B%0A%20%20%20%20BIND(%3Chttp://openbiodiv.net/4B689A17-2541-4F5F-A896-6F0C2EEA3FB4%3E%20AS%20?id).%20%0A%20%20%20%20%20?id%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/TaxonomicNameUsage%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/specificEpithet%3E%20?specificEpithet.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/genus%3E%20?genus.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/family%3E%20?family.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/order%3E%20?order.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/class%3E%20?class.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/phylum%3E%20?phylum.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/kingdom%3E%20?kingdom.%7D%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?taxon.%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/verbatimTaxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%20%20UNION%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?btaxon.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://openbiodiv.net/hasGbifTaxon%3E%20?taxon.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/taxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%7D%20%7D]
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:134)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:127)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.lambda$getResourceServiceTest$0(OpenBiodivUtilTest.java:70)
	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:25)
	... 28 more
Caused by: org.apache.http.client.HttpResponseException: status code: 401
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:66)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:52)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:132)
	... 31 more


java.io.IOException: failed to execute query [PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX prism: <http://prismstandard.org/namespaces/basic/2.0/>
PREFIX doco: <http://purl.org/spar/doco/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
select ?name ?rank ?id ?kingdom ?phylum ?class ?order ?family ?genus ?specificEpithet where { {
    BIND(<http://openbiodiv.net/22A7F215-829B-458A-AEBB-39FFEA6D4A91> AS ?id). 
     ?id <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/TaxonomicNameUsage>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/specificEpithet> ?specificEpithet.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/genus> ?genus.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/family> ?family.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/order> ?order. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/class> ?class. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/phylum> ?phylum.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/kingdom> ?kingdom.}
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?taxon.
      ?taxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/verbatimTaxonRank> ?rank.}
      ?taxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }    UNION
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?btaxon.
      ?btaxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      ?btaxon <http://openbiodiv.net/hasGbifTaxon> ?taxon.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/taxonRank> ?rank.}
      ?btaxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }  } }]

	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:27)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.doLookup(OpenBiodivUtil.java:58)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.retrieveTaxonHierarchyById(OpenBiodivUtil.java:21)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.retrieveTaxonSpecies2(OpenBiodivUtilTest.java:53)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: failed to get [http://graph.openbiodiv.net/repositories/OpenBiodiv2020?query=PREFIX%20fabio:%20%3Chttp://purl.org/spar/fabio/%3E%0APREFIX%20prism:%20%3Chttp://prismstandard.org/namespaces/basic/2.0/%3E%0APREFIX%20doco:%20%3Chttp://purl.org/spar/doco/%3E%0APREFIX%20dc:%20%3Chttp://purl.org/dc/elements/1.1/%3E%0Aselect%20?name%20?rank%20?id%20?kingdom%20?phylum%20?class%20?order%20?family%20?genus%20?specificEpithet%20where%20%7B%20%7B%0A%20%20%20%20BIND(%3Chttp://openbiodiv.net/22A7F215-829B-458A-AEBB-39FFEA6D4A91%3E%20AS%20?id).%20%0A%20%20%20%20%20?id%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/TaxonomicNameUsage%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/specificEpithet%3E%20?specificEpithet.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/genus%3E%20?genus.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/family%3E%20?family.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/order%3E%20?order.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/class%3E%20?class.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/phylum%3E%20?phylum.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/kingdom%3E%20?kingdom.%7D%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?taxon.%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/verbatimTaxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%20%20UNION%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?btaxon.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://openbiodiv.net/hasGbifTaxon%3E%20?taxon.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/taxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%7D%20%7D]
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:134)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:127)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.lambda$getResourceServiceTest$0(OpenBiodivUtilTest.java:70)
	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:25)
	... 28 more
Caused by: org.apache.http.client.HttpResponseException: status code: 401
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:66)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:52)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:132)
	... 31 more
```

**Comment by jhpoelen** [comment]
also confirmed by attached screenshot.

![image](https://user-images.githubusercontent.com/1084872/198135507-8182050d-b5a5-4499-a8d3-f9a6fde842cf.png)

**Comment by jhpoelen** [comment]
@mdmtrv @daniel-mietchen @howkins  any idea why OpenBiodiv is no longer openly available?

**Comment by jhpoelen** [comment]
As far as I can tell, pensoft has moved their Sparql endpoint to:

https://graph.openbiodiv.net/repositories/OpenBiodiv

also, it appears that their namespace prefix has changed from

http://openbiodiv.net 

to 

https://openbiodiv.net 

And, it appears that the endpoint no longer returns csv, but nquads.

These changes cause the existing integrations to no longer work.

**Comment by jhpoelen** [comment]
Hi @vsenderov - I noticed you are still actively working on OpenBiodiv. Just curious who I should contact to ask questions about the project? I am hoping to fix the integration between GloBI/Nomer and the OpenBiodiv universe.

**Comment by vsenderov** [comment]
Hi @jhpoelen.  Thanks for your interest.  I am really glad that you are trying to link to our project. Indeed, OpenBiodiv is actively being developed, but I am not the main maintainer any more.  @mdmtrv (https://github.com/mdmtrv) is the new maintainer now, I will ping her to get in touch with you.

**Comment by mdmtrv** [comment]
Hi all and thanks @vsenderov for the mention,

Is it possible that GloBI is connected to the old OpenBiodiv repo
(OpenBiodiv2020)? We reprocessed everything and moved to a new GraphDB repo
(OpenBiodiv) a few months ago.

Please try that, @jhpoelen and let me know if it worked.
Best,
Marius

**Comment by jhpoelen** [comment]
@vsenderov @mdmtrv thanks for your prompt reply. Hoping to update the integration to continue to benefit from OpenBiodiv .

I am assuming that all uuids (e.g., taxon ids) have been re-minted in reprocessing, so existing openbiodiv links need to be deprecated. 

Just curious: do you keep an archived copy of openbiodiv somewhere? Some publicly available database "dump" of openbiodiv would help me to enable fast integrations with openbiodiv resources via tools like GloBI / Nomer / Elton.

**Comment by mdmtrv** [comment]
Hi  @jhpoelen,

Apologies for the late reply. We have an old archive on Zenodo:
https://zenodo.org/record/5283207#.Y-kuB3ZBy5c but you probably need one
with the pre-processed graph. I will let you know when we upload one to
Zenodo.

Best,
Mariya
