### ISSUE TITLE
known ITIS id [ITIS:168823] fails to be resolved via  https://www.itis.gov:443/ITISWebService/services/ITISService/getAcceptedNamesFromTSN?tsn=168823

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#16]
Even though ITS webpages https://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=168823#null have information about ITIS taxon id 168823 (see attached), an associated web service call fails:

```
failed to find a match for [{externalId=ITIS:168823, name=Caristius japonicus}] in [ITISService]
org.eol.globi.service.PropertyEnricherException: failed to execute query to [https://www.itis.gov:443/ITISWebService/services/ITISService/getAcceptedNamesFromTSN?tsn=168823]
        at org.eol.globi.taxon.ITISService.getResponse(ITISService.java:97)
        at org.eol.globi.taxon.ITISService.enrichWithId(ITISService.java:37)
        at org.eol.globi.taxon.ITISService.enrich(ITISService.java:30)
        at org.eol.globi.taxon.TaxonEnricherImpl.enrichTaxon(TaxonEnricherImpl.java:73)
        at org.eol.globi.taxon.TaxonEnricherImpl.enrichTaxonWithPropertyValue(TaxonEnricherImpl.java:65)
        at org.eol.globi.taxon.TaxonEnricherImpl.enrich(TaxonEnricherImpl.java:34)
        at org.eol.globi.taxon.TaxonEnricherImpl.findTerms(TaxonEnricherImpl.java:110)
        at org.globalbioticinteractions.nomer.util.AppendingRowHandler.onRow(AppendingRowHandler.java:30)
        at org.globalbioticinteractions.nomer.util.MatchUtil.apply(MatchUtil.java:50)
        at org.globalbioticinteractions.nomer.util.MatchUtil.match(MatchUtil.java:25)
        at org.globalbioticinteractions.nomer.cmd.CmdAppend.run(CmdAppend.java:38)
        at org.globalbioticinteractions.nomer.cmd.CmdLine.run(CmdLine.java:18)
        at org.globalbioticinteractions.nomer.cmd.CmdLine.run(CmdLine.java:27)
        at org.globalbioticinteractions.nomer.Nomer.main(Nomer.java:15)
Caused by: org.apache.http.client.HttpResponseException: status code: 404, reason phrase: Not Found
        at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70)
        at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:66)
        at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:52)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
        at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
        at org.eol.globi.util.HttpUtil.executeWithTimer(HttpUtil.java:146)
        at org.eol.globi.taxon.ITISService.getResponse(ITISService.java:95)
        ... 13 more
problem with taxon lookup
```

**Comment by jhpoelen** [comment]
Fixed by ITIS api team.
