### ISSUE TITLE
java.lang.IllegalArgumentException: need non-empty list of names

### ISSUE THREAD

**Issue by nleguillarme** [globalbioticinteractions/nomer#188]
Hi @jhpoelen

With the last version (0.5.13), running the following command 
`echo -e "\tMethylocystis\n\tMethylocella"|nomer append globalnames`

results in the following error:
```
	Methylocystis	SAME_AS	NCBI:133	Methylocystis		genus		| Bacteria | Pseudomonadota | Alphaproteobacteria | Hyphomicrobiales | Methylocystaceae | Methylocystis	NCBI:131567 | NCBI:2 | NCBI:1224 | NCBI:28211 | NCBI:356 | NCBI:31993 | NCBI:133	| superkingdom | phylum | class | order | family | genus		https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=133
	Methylocystis	SAME_AS	WORMS:571351	Methylocystis						https://www.marinespecies.org/aphia.php?p=taxdetails&id=571351
	Methylocystis	SAME_AS	GBIF:3221072	Methylocystis		genus		Bacteria | Proteobacteria | Alphaproteobacteria | Rhizobiales | Beijerinckiaceae | Methylocystis	GBIF:3 | GBIF:111 | GBIF:197 | GBIF:1221 | GBIF:7813 | GBIF:3221072	kingdom | phylum | class | order | family | genus	http://www.gbif.org/species/3221072
	Methylocystis	SAME_AS	OTT:992089	Methylocystis		genus		|  | Bacteria | Proteobacteria | Alphaproteobacteria | Rhizobiales | Methylocystaceae | Methylocystis	OTT:805080 | OTT:93302 | OTT:844192 | OTT:248067 | OTT:683449 | OTT:1091894 | OTT:592899 | OTT:992089	no rank | no rank | domain | phylum | class | order | family | genus		https://tree.opentreeoflife.org/opentree/ottol@992089
	Methylocystis	SAME_AS	ITIS:957581	Methylocystis		Genus		Bacteria | Negibacteria | Proteobacteria | Alphaproteobacteria | Rhizobiales | Methylocystaceae | Methylocystis	ITIS:50 | ITIS:956096 | ITIS:956120 | ITIS:956129 | ITIS:956260 | ITIS:956455 | ITIS:957581	Kingdom | Subkingdom | Phylum | Class | Order | Family | Genus		http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=957581
java.lang.IllegalArgumentException: need non-empty list of names
	at org.eol.globi.taxon.GlobalNamesService2.match(GlobalNamesService2.java:106)
	at org.eol.globi.service.Synonymizer$2.foundTaxonForTerm(Synonymizer.java:53)
	at org.eol.globi.taxon.GlobalNamesService2.noMatch(GlobalNamesService2.java:256)
	at org.eol.globi.taxon.GlobalNamesService2.parseClassification(GlobalNamesService2.java:371)
	at org.eol.globi.taxon.GlobalNamesService2.parseResultNode(GlobalNamesService2.java:236)
	at org.eol.globi.taxon.GlobalNamesService2.parseResult(GlobalNamesService2.java:203)
	at org.eol.globi.taxon.GlobalNamesService2.findTermsForNames(GlobalNamesService2.java:119)
	at org.eol.globi.taxon.GlobalNamesService2.match(GlobalNamesService2.java:108)
	at org.eol.globi.service.Synonymizer.match(Synonymizer.java:45)
	at org.eol.globi.service.TermMatcherHierarchical.match(TermMatcherHierarchical.java:57)
	at org.globalbioticinteractions.nomer.util.AppendingRowHandler.onRow(AppendingRowHandler.java:42)
	at org.globalbioticinteractions.nomer.match.MatchUtil.apply(MatchUtil.java:95)
	at org.globalbioticinteractions.nomer.match.MatchUtil.match(MatchUtil.java:39)
	at org.globalbioticinteractions.nomer.cmd.CmdAppend.run(CmdAppend.java:26)
	at picocli.CommandLine.executeUserObject(CommandLine.java:1939)
	at picocli.CommandLine.access$1300(CommandLine.java:145)
	at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2358)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2352)
	at picocli.CommandLine$RunLast.handle(CommandLine.java:2314)
	at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
	at picocli.CommandLine$RunLast.execute(CommandLine.java:2316)
	at picocli.CommandLine.execute(CommandLine.java:2078)
	at org.globalbioticinteractions.nomer.Nomer.run(Nomer.java:57)
	at org.globalbioticinteractions.nomer.Nomer.main(Nomer.java:46)
```

**Comment by jhpoelen** [comment]
hi @nleguillarme - thanks for reporting this issue and for providing the details!

I was able to reproduce and fix the issue.

With the current development version, the command

```
echo -e "\tMethylocystis\n\tMethylocella"\
| nomer append globalnames
```

produces

```
	Methylocystis	SAME_AS	NCBI:133	Methylocystis		genus		| Bacteria | Pseudomonadota | Alphaproteobacteria | Hyphomicrobiales | Methylocystaceae | Methylocystis	NCBI:131567 | NCBI:2 | NCBI:1224 | NCBI:28211 | NCBI:356 | NCBI:31993 | NCBI:133	| superkingdom | phylum | class | order | family | genus		https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=133
	Methylocystis	SAME_AS	WORMS:571351	Methylocystis								https://www.marinespecies.org/aphia.php?p=taxdetails&id=571351
	Methylocystis	SAME_AS	GBIF:3221072	Methylocystis		genus		Bacteria | Proteobacteria | Alphaproteobacteria | Rhizobiales | Beijerinckiaceae | Methylocystis	GBIF:3 | GBIF:111 | GBIF:197 | GBIF:1221 | GBIF:7813 | GBIF:3221072	kingdom | phylum | class | order | family | genus		http://www.gbif.org/species/3221072
	Methylocystis	SAME_AS	OTT:992089	Methylocystis		genus		|  | Bacteria | Proteobacteria | Alphaproteobacteria | Rhizobiales | Methylocystaceae | Methylocystis	OTT:805080 | OTT:93302 | OTT:844192 | OTT:248067 | OTT:683449 | OTT:1091894 | OTT:592899 | OTT:992089	no rank | no rank | domain | phylum | class | order | family | genus		https://tree.opentreeoflife.org/opentree/ottol@992089
	Methylocystis	SAME_AS	ITIS:957581	Methylocystis		Genus		Bacteria | Negibacteria | Proteobacteria | Alphaproteobacteria | Rhizobiales | Methylocystaceae | Methylocystis	ITIS:50 | ITIS:956096 | ITIS:956120 | ITIS:956129 | ITIS:956260 | ITIS:956455 | ITIS:957581	Kingdom | Subkingdom | Phylum | Class | Order | Family | Genus		http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=957581
	Methylocystis	NONE		Methylocystis								
	Methylocystis	NONE		Methylocystis								
	Methylocystis	SAME_AS	IRMNG:1034928	Methylocystis		genus		Bacteria | Proteobacteria | Alphaproteobacteria | Rhizobiales | Methylocystaceae | Methylocystis	IRMNG:13 | IRMNG:192 | IRMNG:1110 | IRMNG:11800 | IRMNG:114990 | IRMNG:1034928	kingdom | phylum | class | order | family | genus		https://www.irmng.org/aphia.php?p=taxdetails&id=1034928
	Methylocella	SAME_AS	NCBI:120652	Methylocella		genus		| Bacteria | Pseudomonadota | Alphaproteobacteria | Hyphomicrobiales | Beijerinckiaceae | Methylocella	NCBI:131567 | NCBI:2 | NCBI:1224 | NCBI:28211 | NCBI:356 | NCBI:45404 | NCBI:120652	| superkingdom | phylum | class | order | family | genus		https://www.ncbi.nlm.nih.gov/Taxonomy/Browser/wwwtax.cgi?id=120652
	Methylocella	SAME_AS	WORMS:571203	Methylocella								https://www.marinespecies.org/aphia.php?p=taxdetails&id=571203
	Methylocella	SAME_AS	OTT:729645	Methylocella		genus		|  | Bacteria | Proteobacteria | Alphaproteobacteria | Rhizobiales | Beijerinckiaceae | Methylocella	OTT:805080 | OTT:93302 | OTT:844192 | OTT:248067 | OTT:683449 | OTT:1091894 | OTT:377931 | OTT:729645	no rank | no rank | domain | phylum | class | order | family | genus		https://tree.opentreeoflife.org/opentree/ottol@729645
	Methylocella	SAME_AS	ITIS:957579	Methylocella		Genus		Bacteria | Negibacteria | Proteobacteria | Alphaproteobacteria | Rhizobiales | Beijerinckiaceae | Methylocella	ITIS:50 | ITIS:956096 | ITIS:956120 | ITIS:956129 | ITIS:956260 | ITIS:956334 | ITIS:957579	Kingdom | Subkingdom | Phylum | Class | Order | Family | Genus		http://www.itis.gov/servlet/SingleRpt/SingleRpt?search_topic=TSN&search_value=957579
	Methylocella	SAME_AS	IRMNG:1034383	Methylocella		genus		Bacteria | Proteobacteria | Alphaproteobacteria | Rhizobiales | Beijerinckiaceae | Methylocella	IRMNG:13 | IRMNG:192 | IRMNG:1110 | IRMNG:11800 | IRMNG:112997 | IRMNG:1034383	kingdom | phylum | class | order | family | genus		https://www.irmng.org/aphia.php?p=taxdetails&id=1034383
	Methylocella	SAME_AS	GBIF:3220866	Methylocella		genus		Bacteria | Proteobacteria | Alphaproteobacteria | Rhizobiales | Beijerinckiaceae | Methylocella	GBIF:3 | GBIF:111 | GBIF:197 | GBIF:1221 | GBIF:7813 | GBIF:3220866	kingdom | phylum | class | order | family | genus		http://www.gbif.org/species/3220866
```

**Comment by jhpoelen** [comment]
If you'd like to use 0.5.13 and can't wait for 0.5.14 to be released, you can use the following workaround:

```
echo -e "\tMethylocystis\n\tMethylocella"\
| nomer append --properties <(echo "nomer.guess.synonyms=false") globalnames
```

The root cause was that a recently introduced synonymizer (see https://github.com/globalbioticinteractions/nomer/releases/tag/0.5.12) tries to submit and empty list of terms for matching. . . and the globalnames matcher didn't quite appreciate that. 

Hope all is well, and thanks again for reporting the issue.

**Comment by nleguillarme** [comment]
As effective as ever :) Thanks a lot!
