### ISSUE TITLE
openbiodiv sparql endpoint unavailable

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/nomer#28]
Nomer's openbiodiv integration tests failed because the OpenBiodiv sparql endpoint appears to be unavailable. 

 @mdmtrv - please let me know if I have to update any configuration on my end to get the openbiodiv integration working again.
```
java.io.IOException: failed to execute query [PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX prism: <http://prismstandard.org/namespaces/basic/2.0/>
PREFIX doco: <http://purl.org/spar/doco/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
select ?name ?rank ?id ?kingdom ?phylum ?class ?order ?family ?genus ?specificEpithet where { {
    BIND(<http://openbiodiv.net/6A54156A-BE5C-44D7-A9E3-3902DA4CCFAC> AS ?id). 
     ?id <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/TaxonomicNameUsage>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/specificEpithet> ?specificEpithet.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/genus> ?genus.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/family> ?family.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/order> ?order. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/class> ?class. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/phylum> ?phylum.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/kingdom> ?kingdom.}
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?taxon.
      ?taxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/verbatimTaxonRank> ?rank.}
      ?taxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }    UNION
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?btaxon.
      ?btaxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      ?btaxon <http://openbiodiv.net/hasGbifTaxon> ?taxon.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/taxonRank> ?rank.}
      ?btaxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }  } }]

	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:27)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.doLookup(OpenBiodivUtil.java:58)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.retrieveTaxonHierarchyById(OpenBiodivUtil.java:21)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.retrieveTaxonSpecies(OpenBiodivUtilTest.java:36)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: failed to get [http://graph.openbiodiv.net/repositories/OpenBiodiv2020?query=PREFIX%20fabio:%20%3Chttp://purl.org/spar/fabio/%3E%0APREFIX%20prism:%20%3Chttp://prismstandard.org/namespaces/basic/2.0/%3E%0APREFIX%20doco:%20%3Chttp://purl.org/spar/doco/%3E%0APREFIX%20dc:%20%3Chttp://purl.org/dc/elements/1.1/%3E%0Aselect%20?name%20?rank%20?id%20?kingdom%20?phylum%20?class%20?order%20?family%20?genus%20?specificEpithet%20where%20%7B%20%7B%0A%20%20%20%20BIND(%3Chttp://openbiodiv.net/6A54156A-BE5C-44D7-A9E3-3902DA4CCFAC%3E%20AS%20?id).%20%0A%20%20%20%20%20?id%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/TaxonomicNameUsage%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/specificEpithet%3E%20?specificEpithet.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/genus%3E%20?genus.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/family%3E%20?family.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/order%3E%20?order.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/class%3E%20?class.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/phylum%3E%20?phylum.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/kingdom%3E%20?kingdom.%7D%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?taxon.%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/verbatimTaxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%20%20UNION%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?btaxon.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://openbiodiv.net/hasGbifTaxon%3E%20?taxon.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/taxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%7D%20%7D]
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:137)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:130)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.lambda$getResourceServiceTest$0(OpenBiodivUtilTest.java:63)
	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:25)
	... 28 more
Caused by: org.apache.http.client.HttpResponseException: status code: 503, reason phrase: Service Unavailable
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:66)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:52)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:135)
	... 31 more


java.io.IOException: failed to execute query [PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX prism: <http://prismstandard.org/namespaces/basic/2.0/>
PREFIX doco: <http://purl.org/spar/doco/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
select ?name ?rank ?id ?kingdom ?phylum ?class ?order ?family ?genus ?specificEpithet where { {
    BIND(<http://openbiodiv.net/4B689A17-2541-4F5F-A896-6F0C2EEA3FB4> AS ?id). 
     ?id <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/TaxonomicNameUsage>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/specificEpithet> ?specificEpithet.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/genus> ?genus.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/family> ?family.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/order> ?order. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/class> ?class. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/phylum> ?phylum.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/kingdom> ?kingdom.}
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?taxon.
      ?taxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/verbatimTaxonRank> ?rank.}
      ?taxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }    UNION
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?btaxon.
      ?btaxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      ?btaxon <http://openbiodiv.net/hasGbifTaxon> ?taxon.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/taxonRank> ?rank.}
      ?btaxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }  } }]

	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:27)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.doLookup(OpenBiodivUtil.java:58)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.retrieveTaxonHierarchyById(OpenBiodivUtil.java:21)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.retrieveTaxonFamily(OpenBiodivUtilTest.java:24)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: failed to get [http://graph.openbiodiv.net/repositories/OpenBiodiv2020?query=PREFIX%20fabio:%20%3Chttp://purl.org/spar/fabio/%3E%0APREFIX%20prism:%20%3Chttp://prismstandard.org/namespaces/basic/2.0/%3E%0APREFIX%20doco:%20%3Chttp://purl.org/spar/doco/%3E%0APREFIX%20dc:%20%3Chttp://purl.org/dc/elements/1.1/%3E%0Aselect%20?name%20?rank%20?id%20?kingdom%20?phylum%20?class%20?order%20?family%20?genus%20?specificEpithet%20where%20%7B%20%7B%0A%20%20%20%20BIND(%3Chttp://openbiodiv.net/4B689A17-2541-4F5F-A896-6F0C2EEA3FB4%3E%20AS%20?id).%20%0A%20%20%20%20%20?id%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/TaxonomicNameUsage%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/specificEpithet%3E%20?specificEpithet.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/genus%3E%20?genus.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/family%3E%20?family.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/order%3E%20?order.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/class%3E%20?class.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/phylum%3E%20?phylum.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/kingdom%3E%20?kingdom.%7D%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?taxon.%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/verbatimTaxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%20%20UNION%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?btaxon.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://openbiodiv.net/hasGbifTaxon%3E%20?taxon.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/taxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%7D%20%7D]
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:137)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:130)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.lambda$getResourceServiceTest$0(OpenBiodivUtilTest.java:63)
	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:25)
	... 28 more
Caused by: org.apache.http.client.HttpResponseException: status code: 503, reason phrase: Service Unavailable
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:66)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:52)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:135)
	... 31 more


java.io.IOException: failed to execute query [PREFIX fabio: <http://purl.org/spar/fabio/>
PREFIX prism: <http://prismstandard.org/namespaces/basic/2.0/>
PREFIX doco: <http://purl.org/spar/doco/>
PREFIX dc: <http://purl.org/dc/elements/1.1/>
select ?name ?rank ?id ?kingdom ?phylum ?class ?order ?family ?genus ?specificEpithet where { {
    BIND(<http://openbiodiv.net/22A7F215-829B-458A-AEBB-39FFEA6D4A91> AS ?id). 
     ?id <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/TaxonomicNameUsage>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/specificEpithet> ?specificEpithet.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/genus> ?genus.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/family> ?family.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/order> ?order. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/class> ?class. }
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/phylum> ?phylum.}
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/kingdom> ?kingdom.}
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?taxon.
      ?taxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/verbatimTaxonRank> ?rank.}
      ?taxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }    UNION
    { ?id <http://proton.semanticweb.org/protonkm#mentions> ?btaxon.
      ?btaxon <http://www.w3.org/1999/02/22-rdf-syntax-ns#type> <http://openbiodiv.net/ScientificName>.
      ?btaxon <http://openbiodiv.net/hasGbifTaxon> ?taxon.
      OPTIONAL { ?taxon <http://rs.tdwg.org/dwc/terms/taxonRank> ?rank.}
      ?btaxon <http://www.w3.org/2000/01/rdf-schema#label> ?name.
   }  } }]

	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:27)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.doLookup(OpenBiodivUtil.java:58)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtil.retrieveTaxonHierarchyById(OpenBiodivUtil.java:21)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.retrieveTaxonSpecies2(OpenBiodivUtilTest.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.io.IOException: failed to get [http://graph.openbiodiv.net/repositories/OpenBiodiv2020?query=PREFIX%20fabio:%20%3Chttp://purl.org/spar/fabio/%3E%0APREFIX%20prism:%20%3Chttp://prismstandard.org/namespaces/basic/2.0/%3E%0APREFIX%20doco:%20%3Chttp://purl.org/spar/doco/%3E%0APREFIX%20dc:%20%3Chttp://purl.org/dc/elements/1.1/%3E%0Aselect%20?name%20?rank%20?id%20?kingdom%20?phylum%20?class%20?order%20?family%20?genus%20?specificEpithet%20where%20%7B%20%7B%0A%20%20%20%20BIND(%3Chttp://openbiodiv.net/22A7F215-829B-458A-AEBB-39FFEA6D4A91%3E%20AS%20?id).%20%0A%20%20%20%20%20?id%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/TaxonomicNameUsage%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/specificEpithet%3E%20?specificEpithet.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/genus%3E%20?genus.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/family%3E%20?family.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/order%3E%20?order.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/class%3E%20?class.%20%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/phylum%3E%20?phylum.%7D%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/kingdom%3E%20?kingdom.%7D%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?taxon.%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/verbatimTaxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?taxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%20%20UNION%0A%20%20%20%20%7B%20?id%20%3Chttp://proton.semanticweb.org/protonkm%23mentions%3E%20?btaxon.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/1999/02/22-rdf-syntax-ns%23type%3E%20%3Chttp://openbiodiv.net/ScientificName%3E.%0A%20%20%20%20%20%20?btaxon%20%3Chttp://openbiodiv.net/hasGbifTaxon%3E%20?taxon.%0A%20%20%20%20%20%20OPTIONAL%20%7B%20?taxon%20%3Chttp://rs.tdwg.org/dwc/terms/taxonRank%3E%20?rank.%7D%0A%20%20%20%20%20%20?btaxon%20%3Chttp://www.w3.org/2000/01/rdf-schema%23label%3E%20?name.%0A%20%20%20%7D%20%20%7D%20%7D]
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:137)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:130)
	at org.globalbioticinteractions.nomer.util.OpenBiodivUtilTest.lambda$getResourceServiceTest$0(OpenBiodivUtilTest.java:63)
	at org.globalbioticinteractions.util.SparqlClientImpl.query(SparqlClientImpl.java:25)
	... 28 more
Caused by: org.apache.http.client.HttpResponseException: status code: 503, reason phrase: Service Unavailable
	at org.apache.http.impl.client.AbstractResponseHandler.handleResponse(AbstractResponseHandler.java:70)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:66)
	at org.apache.http.impl.client.BasicResponseHandler.handleResponse(BasicResponseHandler.java:52)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:223)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:165)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:140)
	at org.eol.globi.util.HttpUtil.executeAndRelease(HttpUtil.java:135)
	... 31 more


Process finished with exit code 255
```

**Comment by mdmtrv** [comment]
Hi @jhpoelen  and sorry for the late reply. I had to restart GraphDB and it's now working.

**Comment by jhpoelen** [comment]
@mdmtrv thanks for your reply and for restarting openbiodiv's triple store. I've re-enable the integration tests and they passed! Hurrah!
