### ISSUE TITLE
ITIS appender crashes when matching for echo -e "\tDufourea glaboabdominalis_sic"

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/nomer#59]
nomer dump discoverlife | cut -f 1,2 | nomer append itis

nomer dump discoverlife | grep "_sic" | head  | cut -f 1,2

echo -e "\tDufourea glaboabdominalis_sic" | nomer append itis  | cut -f 1,2

Output is below, expected NONE to be returned instead as _sic is not in ITIS

using matcher [itis-taxon-id]

java.lang.NullPointerException
	at org.globalbioticinteractions.nomer.match.CommonTaxonService.match(CommonTaxonService.java:61)
	at org.eol.globi.service.TermMatcherHierarchical.match(TermMatcherHierarchical.java:57)
	at org.globalbioticinteractions.nomer.util.AppendingRowHandler.onRow(AppendingRowHandler.java:34)
	at org.globalbioticinteractions.nomer.match.MatchUtil.apply(MatchUtil.java:76)
	at org.globalbioticinteractions.nomer.match.MatchUtil.match(MatchUtil.java:29)
	at org.globalbioticinteractions.nomer.cmd.CmdAppend.run(CmdAppend.java:11)
	at org.globalbioticinteractions.nomer.cmd.CmdLine.run(CmdLine.java:18)
	at org.globalbioticinteractions.nomer.cmd.CmdLine.run(CmdLine.java:27)
	at org.globalbioticinteractions.nomer.Nomer.main(Nomer.java:15)

**Comment by jhpoelen** [comment]
Fixed in v0.2.6 . Please re-open / comment if the issue remains.
