### ISSUE TITLE
discoverlife dump error

### ISSUE THREAD

**Issue by seltmann** [globalbioticinteractions/nomer#62]
@jhpoelen ran the discoverlife dump and there was an error and the file was empty. Thanks!

Using version 0.2.6

> nomer dump discoverlife > discoverlife-13112021.txt
using matcher [discoverlife-taxon]
DiscoverLife name indexing started...
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.mapdb.Volume$ByteBufferVol (file:/usr/local/bin/nomer) to method java.nio.DirectByteBuffer.cleaner()
WARNING: Please consider reporting this to the maintainers of org.mapdb.Volume$ByteBufferVol
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
java.io.IOError: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	at org.mapdb.StoreDirect.checkHeaders(StoreDirect.java:269)
	at org.mapdb.StoreDirect.<init>(StoreDirect.java:207)
	at org.mapdb.DBMaker.extendStoreDirect(DBMaker.java:971)
	at org.mapdb.DBMaker.makeEngine(DBMaker.java:758)
	at org.mapdb.DBMaker.make(DBMaker.java:701)
	at org.globalbioticinteractions.nomer.match.DiscoverLifeTaxonService.initCache(DiscoverLifeTaxonService.java:151)
	at org.globalbioticinteractions.nomer.match.DiscoverLifeTaxonService.lazyInit(DiscoverLifeTaxonService.java:124)
	at org.globalbioticinteractions.nomer.match.DiscoverLifeTaxonService.match(DiscoverLifeTaxonService.java:52)
	at org.eol.globi.service.TermMatcherHierarchical.match(TermMatcherHierarchical.java:57)
	at org.globalbioticinteractions.nomer.util.AppendingRowHandler.onRow(AppendingRowHandler.java:34)
	at org.globalbioticinteractions.nomer.cmd.CmdDump.run(CmdDump.java:17)
	at org.globalbioticinteractions.nomer.cmd.CmdLine.run(CmdLine.java:18)
	at org.globalbioticinteractions.nomer.cmd.CmdLine.run(CmdLine.java:28)
	at org.globalbioticinteractions.nomer.Nomer.main(Nomer.java:15)
Caused by: java.io.IOException: Wrong index checksum, store was not closed properly and could be corrupted.
	... 14 more

**Comment by jhpoelen** [comment]
@seltmann thanks for sharing your detailed report. Please note that you are seeing a known issue v0.2.6 issue (see https://github.com/globalbioticinteractions/nomer/issues/61), that has been resolved in v0.2.7. Suggest to use the latest Nomer v0.2.8 to benefit from recent fixes and functionality. 

Also, if you get the chance, you might want to install long-term supported versions of OpenJDK 8 or 11  (preferably OpenJDK 8) instead of the current version of java jvm (v13 I believe) that you are using now. These are the versions that Nomer is developed and tested on. 


See attached screenshot from https://access.redhat.com/articles/1299013 .
![Screenshot from 2021-11-13 02-32-26](https://user-images.githubusercontent.com/1084872/141615332-49c85875-2472-4186-ae38-258963ff520b.png)

**Comment by seltmann** [comment]
@jhpoelen Ah! I see that when I install each new version of nomer the download pattern changes. I kept re-installing v0.2.6.
